NPROC_PER_NODE=1 CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
            --model_type qwen2-audio-7b-instruct \
            --model_cache_dir "/user-fs/chenzihao/dingli/models/Qwen/Qwen2-Audio-7B-Instruct" \
            --sft_type full \
            --freeze_parameters 0.999 \
            --additional_trainable_parameters audio_tower \
            --dtype AUTO \
            --template_type AUTO \
            --output_dir "/user-fs/chenzihao/dingli/finetune_qwen2audio/output" \
            --dataset "/user-fs/chenzihao/dingli/finetune_qwen2audio/data/train.jsonl" \
            --dataset_test_ratio 0.01 \
            --num_train_epochs 3 \
            --max_length 1024 \
            --check_dataset_strategy warning \
            --gradient_checkpointing true \
            --batch_size 6 \
            --weight_decay 0.01 \
            --learning_rate 1e-5 \
            --gradient_accumulation_steps 32  \
            --max_grad_norm 0.5 \
            --warmup_ratio 0.03 \
            --eval_steps 100 \
            --save_step 1000 \
            --train_dataset_sample -1 \
            --save_total_limit 10 \
            --report_to tensorboard \
            --logging_steps 10 \
            --lazy_tokenize true